
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SupermarketServiceImplService", targetNamespace = "http://service/", wsdlLocation = "http://139.129.28.167/productservice/supermarketws?wsdl")
public class SupermarketServiceImplService
    extends Service
{

    private final static URL SUPERMARKETSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUPERMARKETSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SUPERMARKETSERVICEIMPLSERVICE_QNAME = new QName("http://service/", "SupermarketServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://139.129.28.167/productservice/supermarketws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUPERMARKETSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SUPERMARKETSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SupermarketServiceImplService() {
        super(__getWsdlLocation(), SUPERMARKETSERVICEIMPLSERVICE_QNAME);
    }

    public SupermarketServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUPERMARKETSERVICEIMPLSERVICE_QNAME, features);
    }

    public SupermarketServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SUPERMARKETSERVICEIMPLSERVICE_QNAME);
    }

    public SupermarketServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUPERMARKETSERVICEIMPLSERVICE_QNAME, features);
    }

    public SupermarketServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SupermarketServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SupermarketService
     */
    @WebEndpoint(name = "SupermarketServiceImplPort")
    public SupermarketService getSupermarketServiceImplPort() {
        return super.getPort(new QName("http://service/", "SupermarketServiceImplPort"), SupermarketService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SupermarketService
     */
    @WebEndpoint(name = "SupermarketServiceImplPort")
    public SupermarketService getSupermarketServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "SupermarketServiceImplPort"), SupermarketService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUPERMARKETSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SUPERMARKETSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SUPERMARKETSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
